### ISSUE TITLE
Only works with LFs, not CRLFs

### ISSUE THREAD

**Issue by anseljh** [commonform/commonform-markup-parse#2]
I had some forms with CRLF line-endings, and `commonform-cli` barfed on them. Took me a while, but I figured out that they needed to be only LFs.

**Comment by kemitchell** [comment]
I'm not averse to adding '\r\n' as a valid line terminator if you'd like to send a PR. I hope you don't mind me saying that it won't be a personal priority.

**Comment by anseljh** [comment]
No problem at all, I will take a shot at it. Please don't take my opening issues as a command for you to do work!

**Comment by kemitchell** [comment]
We're cool, believe me. :sunglasses:

**Comment by kemitchell** [comment]
By the way, Git may be a better place to handle line-ending normalization. [GitHub has a page on it](https://help.github.com/articles/dealing-with-line-endings/).

**Comment by anseljh** [comment]
Thanks — I had seen that, too. Will take another look and try to wrap it up.

**Comment by kemitchell** [comment]
Just for my information: What's your editor on Windows?

**Comment by anseljh** [comment]
Atom

**Comment by kemitchell** [comment]
http://editorconfig.org/ should work. Maybe with a plugin.
